### ISSUE TITLE
Release for common jvm

### ISSUE THREAD

**Issue by Cyberavater** [vova7878/PanamaPort#2]
It seems I can only add this dependency on the Android module. I want to use it for the common JVM 8 or 9 modules, which can be used in desktop JVM and Android. If I use official for JVM and this one DVM (Dalvik Virtual Machine), I'll have a lot of code repetition.
If there is no compiled native code in this project maybe you can release this as a jar instead of aar?

**Comment by vova7878** [comment]
This library is specific to android, it cannot be used on desktop JVM. I understand that you want to use one code on different platforms, but it seems that this is not possible.

My code could be moved to the java.lang.foreing package, but then the build process would have to be changed a lot because of the module system. The same package cannot be present in different modules, but this is necessary to use the library. An additional complication arises with VarHandles - the library uses its analogue, and even if all classes are moved to java.lang, this will not solve the conflict.

**Comment by Cyberavater** [comment]
I think we are looking at it differently.
1. Moving to java.lang. foreign.
- I'm not sure why we would even want that. When using this lib both jvm desktop and android dvm are expected to import from your namespace. It'll be like we don't even know(or care) if the official panama exists.

2. VarHandles 
- I don't know of the specifics but does this use any Android-specific native code? if not (ie, it uses pure java) then this project can indeed be used for jvm 8 desktop as well.

Finally what I'm saying is, that when the user is using this port they're using a fully separate implementation of the official Panama in a different namespace (even on desktop jvm).

**Comment by vova7878** [comment]
No, the library does not use native code, but that does not mean it will work on desktop jvm. It will ONLY work on android, because the code is very specific to art (android runtime). There is a lot of reflection and unsafe code used there. Things are even worse with runtime code generation - android uses the .dex format and cannot use the .class format, for the desktop jvm it's exactly opposite.

If you need a single interface on Android and PC, you will have to make it yourself and when building on different platforms, select the one you need in gradle
